#!/usr/bin/env php
<?php
if (!file_exists('vendor/autoload.php')) {
    die(
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'curl -sS https://getcomposer.org/installer | php' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
}
require 'vendor/autoload.php';

$app = new Pails\Console\PailsApplication();

$app->run();

